sudo: required

language: node_js

node_js:
  - 6.1

services:
  - docker

install:
  - cd $TRAVIS_BUILD_DIR
  - cd src
  - npm install

before_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi'

after_success:
  - cd $TRAVIS_BUILD_DIR
  - docker build -t "davecss/result:latest" -t "davecss/result:1.0.$TRAVIS_BUILD_NUMBER" .
  - cd src
  - ls

deploy:
  provider: script
  skip_cleanup: true
  script: docker push davecss/result
  on:
    branch: master
